import type { AiReview } from "@/lib/ai/review";
import { fmtDate } from "./portal";

const SEVERITY = {
  high: "badge-danger",
  medium: "badge-warning",
  low: "badge-neutral",
} as const;

export function AiReviewCard({ review }: { review: AiReview }) {
  return (
    <div className="space-y-4 text-sm">
      <p className="text-[0.95rem] leading-relaxed">{review.summary}</p>
      {review.flags.length > 0 && (
        <div>
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Flags</h3>
          <ul className="space-y-2">
            {review.flags.map((f, i) => (
              <li key={i} className="flex gap-2">
                <span className={`badge ${SEVERITY[f.severity]} h-fit capitalize`}>{f.severity}</span>
                <span>
                  <span className="font-medium">{f.title}.</span> {f.detail}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
      {review.missingInfo.length > 0 && (
        <div>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Missing or unclear</h3>
          <ul className="list-disc space-y-1 pl-5">
            {review.missingInfo.map((m, i) => (
              <li key={i}>{m}</li>
            ))}
          </ul>
        </div>
      )}
      {review.followUpQuestions.length > 0 && (
        <div>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Ask the applicant</h3>
          <ul className="list-disc space-y-1 pl-5">
            {review.followUpQuestions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>
      )}
      <p className="text-xs text-[var(--muted)]">
        AI-generated by {review.model} on {fmtDate(review.reviewedAt)}. Check against the answers before relying on it.
      </p>
    </div>
  );
}
